// Generated by CoffeeScript 1.10.0
(function() {
  var applyTo, bindFn, myArray, myObj, myObj2;

  myObj = {
    num: 5
  };

  myObj2 = {
    num: 10
  };

  applyTo = function(a, b, c) {
    return console.log(this.num + a + b + c);
  };

  applyTo(1, 2, 3);

  applyTo.call(myObj, 1, 2, 3);

  myArray = [5, 6, 7];

  applyTo.apply(myObj, myArray);

  applyTo.apply(myObj2, myArray);

  bindFn = applyTo.bind(myObj);

  bindFn(1, 2, 3);

}).call(this);
