// Generated by CoffeeScript 1.10.0
(function() {
  var checkNegativeNumber, dragElement, dropElement, minusElement, numberElement, plusElement;

  dragElement = document.querySelector('.draggable');

  dropElement = document.querySelector('.droppable');

  minusElement = document.querySelector('.minus');

  plusElement = document.querySelector('.plus');

  numberElement = document.querySelectorAll('.number');

  dragElement.addEventListener('dragstart', function(event) {
    return dragElement.classList.add('dragAnim');
  });

  dragElement.addEventListener('dragend', function(event) {
    return dragElement.classList.remove('dragAnim');
  });

  dropElement.addEventListener('dragover', function(event) {
    return event.preventDefault();
  });

  dropElement.addEventListener('drop', function(event) {
    dropElement.classList.add('dragAnim');
    setTimeout((function() {
      return dropElement.classList.remove('dragAnim');
    }), 500);
    numberElement[1].innerHTML = parseInt(numberElement[1].innerHTML) + parseInt(numberElement[0].innerHTML);
    return checkNegativeNumber();
  });

  dropElement.addEventListener('dragstart', function(event) {
    return dropElement.classList.add('dragAnim');
  });

  dropElement.addEventListener('dragend', function(event) {
    dropElement.classList.remove('dragAnim');
    numberElement[1].innerHTML = parseInt(numberElement[1].innerHTML) - parseInt(numberElement[0].innerHTML);
    return checkNegativeNumber();
  });

  minusElement.addEventListener('click', function(event) {
    numberElement[0].innerHTML = parseInt(numberElement[0].innerHTML) - 1;
    return checkNegativeNumber();
  });

  plusElement.addEventListener('click', function(event) {
    return numberElement[0].innerHTML = parseInt(numberElement[0].innerHTML) + 1;
  });

  checkNegativeNumber = function() {
    if (parseInt(numberElement[1].innerHTML) < 0) {
      numberElement[1].innerHTML = 0;
    }
    if (parseInt(numberElement[0].innerHTML) < 1) {
      return numberElement[0].innerHTML = 1;
    }
  };

}).call(this);
